[tox]
requires =
	tox>=4
env_list = lint, integration

[testenv:lint]
description = run linters
skip_install = true
deps =
	yamllint
commands = 
	yamllint --no-warnings rockcraft.yaml spread.yaml spread/tests

[testenv:integration]
description = run all operator integration tests via spread
skip_install = true
pass_env =
    CI
allowlist_externals =
	rockcraft
commands = 
	rockcraft test

[testenv:replica-set-integration]
description = run replica set operator integration tests via spread
skip_install = true
pass_env =
    CI
allowlist_externals =
	rockcraft
commands =
	rockcraft test craft:ubuntu-24.04:spread/tests/replica-set

[testenv:sharding-integration]
description = run sharding operator integration tests via spread
skip_install = true
allowlist_externals =
	rockcraft
pass_env =
    CI
commands = 
	rockcraft test craft:ubuntu-24.04:spread/tests/sharding
