name: Build ROCK

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: mongodb-rock
          path: ${{ steps.rockcraft.outputs.rock }}
