name: Build rock

on:
  workflow_call:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install yq
          sudo snap install rockcraft --classic --edge
      - name: Build rock
        run: |
          rockcraft pack
      - name: Upload locally built rock artifact
        uses: actions/upload-artifact@v3
        with:
          name: mongodb-rock
          path: charmed-mongodb_*_amd64.rock
