name: Operator Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v41.0.0
    permissions:
      actions: read # Needed for GitHub API call to get workflow version
      contents: read

  integration:
    name: Integration tests | ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 240
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download rock package(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*--platform-${{ matrix.arch }}
          merge-multiple: true

      - name: Set up spread environment
        run: |
          snap list lxd || sudo snap install lxd
          sudo adduser "$USER" lxd
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT

          snap list rockcraft || sudo snap install rockcraft --classic
          pipx install tox

      - name: Integration Tests
        run: |
          TOX_BIN="$(pipx environment --value PIPX_BIN_DIR)/tox"
          sg lxd -c "${TOX_BIN} -e integration"
