name: Operator Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  integration:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        env: [integration, ha-integration, tls-integration]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - uses: actions/download-artifact@v3
        with:
          name: mongodb-rock
      - name: Install tox
        run: python3 -m pip install tox
      - name: Integration Tests
        run: sg microk8s -c "tox -e ${{ matrix.env }}"
