name: Operator Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: build
    strategy:
      matrix:
        env: [integration, ha-integration, tls-integration]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Setup Docker
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
          sudo apt install -y uidmap
      - uses: actions/download-artifact@v3
        with:
          name: mongodb-rock
      - name: Install tox
        run: python3 -m pip install tox
      - name: Integration Tests
        run: sg microk8s -c "tox -e ${{ matrix.env }}"
