on:
  workflow_call:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install Helm
        run: /usr/bin/sudo snap install helm3
      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Install tox
        run: python3 -m pip install tox
      - name: Integration Tests
        run: sg microk8s -c "tox -e integration"
  ha-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install Helm
        run: /usr/bin/sudo snap install helm3
      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Install tox
        run: python3 -m pip install tox
      - name: HA Integration Tests
        run: sg microk8s -c "tox -e ha-integration"
  tls-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install Helm
        run: /usr/bin/sudo snap install helm3
      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Install tox
        run: python3 -m pip install tox
      - name: TLS Integration Tests
        run: sg microk8s -c "tox -e tls-integration"
