name: trivy
on:
  push:
    branches:
      - 6-22.04
      - 5-22.04
  pull_request:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ""
jobs:
  build:
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v29.0.1
  scan:
    name: Trivy scan and sbom generation
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install rockcraft (for skopeo)
        run: |
          sudo snap install rockcraft --classic --edge
      - name: Get Artifact Name
        id: artifact
        run: |
          BASE_ARTIFACT=$(make help | grep 'Artifact: ')
          echo "base_artifact_name=${BASE_ARTIFACT#'Artifact: '}" >> $GITHUB_OUTPUT
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: charmed-mongodb
          path: charmed-mongodb
      - name: Import locally
        run: |
          # Unpack artifact
          mv charmed-mongodb/${{ steps.artifact.outputs.base_artifact_name }} .
          sudo rockcraft.skopeo --insecure-policy copy \
            docker-archive:${{ steps.artifact.outputs.base_artifact_name }} \
            docker-daemon:trivy/charmed-mongodb:test
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "trivy/charmed-mongodb:test"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "MEDIUM,HIGH,CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
          ref: ${{ inputs.branch }}

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          format: "spdx-json"
          output: "dependency-results.sbom.json"
          image-ref: "trivy/charmed-mongodb:test"
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          severity: "MEDIUM,HIGH,CRITICAL"
          scanners: "vuln"

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: "${{ github.workspace }}/dependency-results.sbom.json"
          retention-days: 90
